name: autocheck

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 23 8  * * *

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
          python-version: '3.8'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests
           |python -m pip install --upgrade pip
           |apt-get install pip3
           |pip3 install Pysocks
           |pip3 install requests
           |wget https://raw.githubusercontent.com/qinghuas/socks5-install/master/socks5.sh;bash socks5.sh
           |socks5 install
           |socks5 user add admin 123456
    - name: sign
      env:
       account: ${{ secrets.account }}
       pwd: ${{ secrets.pwd }}
       TG_TOKEN: ${{ secrets.TG_TOKEN }}
       CHAT_ID: ${{ secrets.CHAT_ID }}
       lng: ${{ secrets.lng }}
       lat: ${{ secrets.lat }}
       ipadress: ${{ secrets.ipadress }}
       port: ${{ secrets.port }}
       username: ${{ secrets.username }}
       password: ${{ secrets.password }}
      run: |
       python3 check.py
