name: autocheck

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 23 8  * * *

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
          python-version: '3.6'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests
           sudo apt-get install python3-pip
           pip3 install Pysocks

    - name: sign
      env:
       account: ${{ secrets.account }}
       pwd: ${{ secrets.pwd }}
       TG_TOKEN: ${{ secrets.TG_TOKEN }}
       CHAT_ID: ${{ secrets.CHAT_ID }}
       lng: ${{ secrets.lng }}
       lat: ${{ secrets.lat }}
      run: |
       python3 check.py
